### ISSUE TITLE
--history-api-fallback doesn't work?

### ISSUE THREAD

**Issue by ttyao** [reactjs/react-router-tutorial#11]
I tried to follow lesson 10 to get clean urls but the server always can't solve `/repos` even after I added `--history-api-fallback` and changed the paths in index.html, and restarted the server. Any idea what might go wrong?

**Comment by mightymaru** [comment]
If you copied the line above the full command there is a typo in the docs.

The doc says: 
--history-fallback-api
instead of:
"start": "webpack-dev-server --inline --content-base . --history-api-fallback"

Double check that you didn't make the same mistake I did (reversed the order of fallback and api). 

Also make sure you have the dot in for current directory after content base.

**Comment by tscok** [comment]
Stumbled upon this typo too :(

` --history-api-fallback`, without the dot, worked for me.

**Comment by matthewjones555** [comment]
I've created a pull request to fix this issue.
