### ISSUE TITLE
Gitbook

### ISSUE THREAD

**Issue by rkrdo** [reactjs/react-router-tutorial#34]
Any plans on publishing the tutorial on [Gitbook](https://www.gitbook.com/)?

**Comment by TomasAnderson** [comment]
In Windows it should be 

    $env:NODE_ENV="dev"

followed by

    npm start

**Comment by calebmichaelsanchez** [comment]
@TomasAnderson: I think you may have commented on the wrong issue.

**Comment by MsUzoAgu** [comment]
@timdorr: I have never used [Gitbook](https://www.gitbook.com/) but I would love to help out especially since I am working through the tutorial right now. 

As I am relatively new to JS/React (primary language is Ruby), I have loads of questions and think that maybe writing/explaining the tutorial from a beginner's mindset might be helpful for people (on the otherhand it would probably be annoying to experienced devs). 

Let me know what you think.

**Comment by timdorr** [comment]
@MsUzoAgu There are other tutorials better suited for that. This isn't an intro to React or modern JS dev, it's an intro to this library. I would read other tutorials to learn the fundamentals about things like Webpack and React.

**Comment by timdorr** [comment]
Given that this is a code-oriented tutorial, I don't think a Gitbook is the right format. I'll close this out for now.
